name: deploy
on: workflow_dispatch

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@master
              with:
                  node-version: 19
            - run: npm ci
            - run: npm run build
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: "release.tar.gz,main.js,manifest.json"
